import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context/authContext";
import { MockDataProvider } from "@/context/mockDataContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Configuração de páginas (não usado atualmente)
/*
const pages = [
  {
    label: "Dashboard",
    icon: <MdOutlineDashboard />,
    link: "/",
  },
  {
    label: "Nova Transação",
    icon: <FaMoneyBills />,
    link: "new-transaction",
  },
];
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`antialiased`}>
        <AuthProvider>
          <MockDataProvider>{children}</MockDataProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
