import type { Metadata } from "next";
import "./globals.css";
import { MockDataProvider } from "@/context/mockDataContext";
import { MdOutlineDashboard } from "react-icons/md";
import { FaMoneyBills } from "react-icons/fa6";
import Sidebar, { PagesTypeSidebar } from "@/components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pages = [
  {
    label: "Dashboard",
    icon: <MdOutlineDashboard />,
    link: "/",
  },
  {
    label: "Nova Transação",
    icon: <FaMoneyBills />,
    link: "new-transaction",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`ntialiased`}>
        <div className="flex flex-row w-full min-h-full">
          <Sidebar pages={pages} />
          <div className="w-dvw min-h-[100vh] p-[4.5rem] bg-[#f9fafb]">
            <MockDataProvider>{children}</MockDataProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
